// @routes-hash 52201d0c388f9a105b18d6b323ed5447
import { Express } from "express";

import route1 from "./routes/agents/clearMemory";
import route2 from "./routes/agents/getMemory";
import route3 from "./routes/artStyle/addArtStyle";
import route4 from "./routes/artStyle/editArtStyle";
import route5 from "./routes/artStyle/extractStylePrompt";
import route6 from "./routes/artStyle/getArtStyle";
import route7 from "./routes/assets/addAssets";
import route8 from "./routes/assets/addAudioAssets";
import route9 from "./routes/assets/batchDelete";
import route10 from "./routes/assets/batchGenerationData";
import route11 from "./routes/assets/delAssets";
import route12 from "./routes/assets/delImage";
import route13 from "./routes/assets/getAssetsApi";
import route14 from "./routes/assets/getImage";
import route15 from "./routes/assets/getMaterialData";
import route16 from "./routes/assets/importFromLibrary";
import route17 from "./routes/assets/importFromProject";
import route18 from "./routes/assets/pollingImageAssets";
import route19 from "./routes/assets/pollingPromptAssets";
import route20 from "./routes/assets/saveAssets";
import route21 from "./routes/assets/updateAssets";
import route22 from "./routes/assets/updateAudioAssets";
import route23 from "./routes/assets/uploadClip";
import route24 from "./routes/assetsGenerate/batchGenerateImageAssets";
import route25 from "./routes/assetsGenerate/batchPolishAssetsPrompt";
import route26 from "./routes/assetsGenerate/cancelGenerate";
import route27 from "./routes/assetsGenerate/generateAssets";
import route28 from "./routes/assetsGenerate/polishAssetsPrompt";
import route29 from "./routes/common/getBigImage";
import route30 from "./routes/cornerScape/batchBindAudio";
import route31 from "./routes/cornerScape/getAllAssets";
import route32 from "./routes/cornerScape/pollingAudio";
import route33 from "./routes/cornerScape/updateAssetsAudio";
import route34 from "./routes/general/generalStatistics";
import route35 from "./routes/general/getSingleProject";
import route36 from "./routes/general/updateProject";
import route37 from "./routes/library-assets/[id]";
import route38 from "./routes/library-assets/index";
import route39 from "./routes/library/folders/[id]";
import route40 from "./routes/library/folders/index";
import route41 from "./routes/login/login";
import route42 from "./routes/modelSelect/getModelDetail";
import route43 from "./routes/modelSelect/getModelList";
import route44 from "./routes/novel/addNovel";
import route45 from "./routes/novel/batchDeleteNovel";
import route46 from "./routes/novel/delNovel";
import route47 from "./routes/novel/event/batchDeleteEvent";
import route48 from "./routes/novel/event/deletEvent";
import route49 from "./routes/novel/event/generateEvents";
import route50 from "./routes/novel/event/getEvent";
import route51 from "./routes/novel/getNovel";
import route52 from "./routes/novel/getNovelData";
import route53 from "./routes/novel/getNovelEventState";
import route54 from "./routes/novel/getNovelIndex";
import route55 from "./routes/novel/updateNovel";
import route56 from "./routes/oss/getFile";
import route57 from "./routes/oss/uploadFile";
import route58 from "./routes/other/deleteAllData";
import route59 from "./routes/other/getVersion";
import route60 from "./routes/production/assets/batchGenerateAssetsImage";
import route61 from "./routes/production/assets/deleteAssetsDireve";
import route62 from "./routes/production/assets/pollingImage";
import route63 from "./routes/production/assets/updateAssetsUrl";
import route64 from "./routes/production/editImage/generateFlowImage";
import route65 from "./routes/production/editImage/getImageDefaultModle";
import route66 from "./routes/production/editImage/getImageFlow";
import route67 from "./routes/production/editImage/saveImageFlow";
import route68 from "./routes/production/editImage/updateImageFlow";
import route69 from "./routes/production/editImage/uploadImage";
import route70 from "./routes/production/getFlowData";
import route71 from "./routes/production/getStoryboardData";
import route72 from "./routes/production/saveFlowData";
import route73 from "./routes/production/storyboard/addStoryboard";
import route74 from "./routes/production/storyboard/batchAddStoryboardInfo";
import route75 from "./routes/production/storyboard/batchDelete";
import route76 from "./routes/production/storyboard/batchGenerateImage";
import route77 from "./routes/production/storyboard/downPreviewImage";
import route78 from "./routes/production/storyboard/editStoryboardInfo";
import route79 from "./routes/production/storyboard/generationTasks";
import route80 from "./routes/production/storyboard/getStoryboardData";
import route81 from "./routes/production/storyboard/pollingImage";
import route82 from "./routes/production/storyboard/previewImage";
import route83 from "./routes/production/storyboard/removeFrame";
import route84 from "./routes/production/storyboard/updateStoryboardUrl";
import route85 from "./routes/production/workbench/addTrack";
import route86 from "./routes/production/workbench/batchGeneratePrompt";
import route87 from "./routes/production/workbench/batchGenerateVideo";
import route88 from "./routes/production/workbench/checkVideoPrompt";
import route89 from "./routes/production/workbench/checkVideoStateList";
import route90 from "./routes/production/workbench/deleteTrack";
import route91 from "./routes/production/workbench/delVideo";
import route92 from "./routes/production/workbench/generateVideo";
import route93 from "./routes/production/workbench/generateVideoPrompt";
import route94 from "./routes/production/workbench/getAudioBindAssetsList";
import route95 from "./routes/production/workbench/getFileUrl";
import route96 from "./routes/production/workbench/getGenerateData";
import route97 from "./routes/production/workbench/getVideoList";
import route98 from "./routes/production/workbench/selectVideo";
import route99 from "./routes/production/workbench/updateVideoDuration";
import route100 from "./routes/production/workbench/updateVideoPrompt";
import route101 from "./routes/project/addDirectorManual";
import route102 from "./routes/project/addProject";
import route103 from "./routes/project/addVisualManual";
import route104 from "./routes/project/deleteDirectorManual";
import route105 from "./routes/project/deleteVisualManual";
import route106 from "./routes/project/delProject";
import route107 from "./routes/project/editDirectorlManual";
import route108 from "./routes/project/editProject";
import route109 from "./routes/project/editVisualManual";
import route110 from "./routes/project/getModelDetails";
import route111 from "./routes/project/getProject";
import route112 from "./routes/project/getVisualManual";
import route113 from "./routes/project/queryDirectorManual";
import route114 from "./routes/project/visualManual";
import route115 from "./routes/quickVideo/addShot";
import route116 from "./routes/quickVideo/bindShotFirstFrame";
import route117 from "./routes/quickVideo/confirmStage";
import route118 from "./routes/quickVideo/createProject";
import route119 from "./routes/quickVideo/createSession";
import route120 from "./routes/quickVideo/getAssetBoard";
import route121 from "./routes/quickVideo/getMediaUrls";
import route122 from "./routes/quickVideo/getMetrics";
import route123 from "./routes/quickVideo/getTimeline";
import route124 from "./routes/quickVideo/getWorkbench";
import route125 from "./routes/quickVideo/listSessions";
import route126 from "./routes/quickVideo/removeShot";
import route127 from "./routes/quickVideo/resolveAssets";
import route128 from "./routes/quickVideo/retryShot";
import route129 from "./routes/quickVideo/updateBrief";
import route130 from "./routes/quickVideo/updateConfig";
import route131 from "./routes/quickVideo/updateModels";
import route132 from "./routes/quickVideo/updateSession";
import route133 from "./routes/quickVideo/updateShot";
import route134 from "./routes/register/register";
import route135 from "./routes/script/addScript";
import route136 from "./routes/script/batchAddScript";
import route137 from "./routes/script/delScript";
import route138 from "./routes/script/exportScript";
import route139 from "./routes/script/extractAssets";
import route140 from "./routes/script/getAiRegex";
import route141 from "./routes/script/getScrptApi";
import route142 from "./routes/script/pollScriptAssets";
import route143 from "./routes/script/updateScript";
import route144 from "./routes/scriptAgent/getPlanData";
import route145 from "./routes/scriptAgent/setPlanData";
import route146 from "./routes/scriptAgent/updateData";
import route147 from "./routes/setting/about/checkUpdate";
import route148 from "./routes/setting/about/downloadApp";
import route149 from "./routes/setting/agentDeploy/agentSetKey";
import route150 from "./routes/setting/agentDeploy/deployAgentModel";
import route151 from "./routes/setting/agentDeploy/getAgentDeploy";
import route152 from "./routes/setting/agentDeploy/getAgentUseMode";
import route153 from "./routes/setting/agentDeploy/updateAgentModel";
import route154 from "./routes/setting/agentDeploy/updateUseMode";
import route155 from "./routes/setting/dbConfig/clearData";
import route156 from "./routes/setting/dbConfig/clearTable";
import route157 from "./routes/setting/dbConfig/dbInfo";
import route158 from "./routes/setting/dbConfig/exportData";
import route159 from "./routes/setting/dbConfig/importData";
import route160 from "./routes/setting/dev/getSwitchAiDevTool";
import route161 from "./routes/setting/dev/updateSwitchAiDevTool";
import route162 from "./routes/setting/fileManagement/openFolder";
import route163 from "./routes/setting/getTextModel";
import route164 from "./routes/setting/loginConfig/getUser";
import route165 from "./routes/setting/loginConfig/updateUserPwd";
import route166 from "./routes/setting/memoryConfig/delAllMemory";
import route167 from "./routes/setting/memoryConfig/getMemory";
import route168 from "./routes/setting/memoryConfig/sureMemory";
import route169 from "./routes/setting/modelMap/bindingPrompt";
import route170 from "./routes/setting/modelMap/deletePrompt";
import route171 from "./routes/setting/modelMap/getImageAndVideoModel";
import route172 from "./routes/setting/modelMap/getPromptList";
import route173 from "./routes/setting/modelMap/savePrompt";
import route174 from "./routes/setting/modelMap/updatePrompt";
import route175 from "./routes/setting/promptManage/getPrompt";
import route176 from "./routes/setting/promptManage/updatePrompt";
import route177 from "./routes/setting/skillManagement/getSkillContent";
import route178 from "./routes/setting/skillManagement/getSkillList";
import route179 from "./routes/setting/skillManagement/saveSkillContent";
import route180 from "./routes/setting/vendorConfig/addVendor";
import route181 from "./routes/setting/vendorConfig/addVendorModel";
import route182 from "./routes/setting/vendorConfig/addVendorModelSpec";
import route183 from "./routes/setting/vendorConfig/deleteVendor";
import route184 from "./routes/setting/vendorConfig/deleteVendorModelSpec";
import route185 from "./routes/setting/vendorConfig/delVendorModel";
import route186 from "./routes/setting/vendorConfig/enableVendor";
import route187 from "./routes/setting/vendorConfig/getCodeByLink";
import route188 from "./routes/setting/vendorConfig/getVendorList";
import route189 from "./routes/setting/vendorConfig/modelTest";
import route190 from "./routes/setting/vendorConfig/modelTest/imageTest";
import route191 from "./routes/setting/vendorConfig/modelTest/textTest";
import route192 from "./routes/setting/vendorConfig/modelTest/videoTest";
import route193 from "./routes/setting/vendorConfig/updateCode";
import route194 from "./routes/setting/vendorConfig/updateVendorInputs";
import route195 from "./routes/setting/vendorConfig/updateVendorModelSpec";
import route196 from "./routes/setting/vendorConfig/upVendorModel";
import route197 from "./routes/task/getProject";
import route198 from "./routes/task/getTaskApi";
import route199 from "./routes/task/getTaskCategories";
import route200 from "./routes/task/taskDetails";
import route201 from "./routes/test/test";
import route202 from "./routes/quickVideo/generateConfirm";

export default async (app: Express) => {
  app.use("/api/agents/clearMemory", route1);
  app.use("/api/agents/getMemory", route2);
  app.use("/api/artStyle/addArtStyle", route3);
  app.use("/api/artStyle/editArtStyle", route4);
  app.use("/api/artStyle/extractStylePrompt", route5);
  app.use("/api/artStyle/getArtStyle", route6);
  app.use("/api/assets/addAssets", route7);
  app.use("/api/assets/addAudioAssets", route8);
  app.use("/api/assets/batchDelete", route9);
  app.use("/api/assets/batchGenerationData", route10);
  app.use("/api/assets/delAssets", route11);
  app.use("/api/assets/delImage", route12);
  app.use("/api/assets/getAssetsApi", route13);
  app.use("/api/assets/getImage", route14);
  app.use("/api/assets/getMaterialData", route15);
  app.use("/api/assets/importFromLibrary", route16);
  app.use("/api/assets/importFromProject", route17);
  app.use("/api/assets/pollingImageAssets", route18);
  app.use("/api/assets/pollingPromptAssets", route19);
  app.use("/api/assets/saveAssets", route20);
  app.use("/api/assets/updateAssets", route21);
  app.use("/api/assets/updateAudioAssets", route22);
  app.use("/api/assets/uploadClip", route23);
  app.use("/api/assetsGenerate/batchGenerateImageAssets", route24);
  app.use("/api/assetsGenerate/batchPolishAssetsPrompt", route25);
  app.use("/api/assetsGenerate/cancelGenerate", route26);
  app.use("/api/assetsGenerate/generateAssets", route27);
  app.use("/api/assetsGenerate/polishAssetsPrompt", route28);
  app.use("/api/common/getBigImage", route29);
  app.use("/api/cornerScape/batchBindAudio", route30);
  app.use("/api/cornerScape/getAllAssets", route31);
  app.use("/api/cornerScape/pollingAudio", route32);
  app.use("/api/cornerScape/updateAssetsAudio", route33);
  app.use("/api/general/generalStatistics", route34);
  app.use("/api/general/getSingleProject", route35);
  app.use("/api/general/updateProject", route36);
  app.use("/api/library-assets/:id", route37);
  app.use("/api/library-assets", route38);
  app.use("/api/library/folders/:id", route39);
  app.use("/api/library/folders", route40);
  app.use("/api/login/login", route41);
  app.use("/api/modelSelect/getModelDetail", route42);
  app.use("/api/modelSelect/getModelList", route43);
  app.use("/api/novel/addNovel", route44);
  app.use("/api/novel/batchDeleteNovel", route45);
  app.use("/api/novel/delNovel", route46);
  app.use("/api/novel/event/batchDeleteEvent", route47);
  app.use("/api/novel/event/deletEvent", route48);
  app.use("/api/novel/event/generateEvents", route49);
  app.use("/api/novel/event/getEvent", route50);
  app.use("/api/novel/getNovel", route51);
  app.use("/api/novel/getNovelData", route52);
  app.use("/api/novel/getNovelEventState", route53);
  app.use("/api/novel/getNovelIndex", route54);
  app.use("/api/novel/updateNovel", route55);
  app.use("/api/oss/getFile", route56);
  app.use("/api/oss/uploadFile", route57);
  app.use("/api/other/deleteAllData", route58);
  app.use("/api/other/getVersion", route59);
  app.use("/api/production/assets/batchGenerateAssetsImage", route60);
  app.use("/api/production/assets/deleteAssetsDireve", route61);
  app.use("/api/production/assets/pollingImage", route62);
  app.use("/api/production/assets/updateAssetsUrl", route63);
  app.use("/api/production/editImage/generateFlowImage", route64);
  app.use("/api/production/editImage/getImageDefaultModle", route65);
  app.use("/api/production/editImage/getImageFlow", route66);
  app.use("/api/production/editImage/saveImageFlow", route67);
  app.use("/api/production/editImage/updateImageFlow", route68);
  app.use("/api/production/editImage/uploadImage", route69);
  app.use("/api/production/getFlowData", route70);
  app.use("/api/production/getStoryboardData", route71);
  app.use("/api/production/saveFlowData", route72);
  app.use("/api/production/storyboard/addStoryboard", route73);
  app.use("/api/production/storyboard/batchAddStoryboardInfo", route74);
  app.use("/api/production/storyboard/batchDelete", route75);
  app.use("/api/production/storyboard/batchGenerateImage", route76);
  app.use("/api/production/storyboard/downPreviewImage", route77);
  app.use("/api/production/storyboard/editStoryboardInfo", route78);
  app.use("/api/production/storyboard/generationTasks", route79);
  app.use("/api/production/storyboard/getStoryboardData", route80);
  app.use("/api/production/storyboard/pollingImage", route81);
  app.use("/api/production/storyboard/previewImage", route82);
  app.use("/api/production/storyboard/removeFrame", route83);
  app.use("/api/production/storyboard/updateStoryboardUrl", route84);
  app.use("/api/production/workbench/addTrack", route85);
  app.use("/api/production/workbench/batchGeneratePrompt", route86);
  app.use("/api/production/workbench/batchGenerateVideo", route87);
  app.use("/api/production/workbench/checkVideoPrompt", route88);
  app.use("/api/production/workbench/checkVideoStateList", route89);
  app.use("/api/production/workbench/deleteTrack", route90);
  app.use("/api/production/workbench/delVideo", route91);
  app.use("/api/production/workbench/generateVideo", route92);
  app.use("/api/production/workbench/generateVideoPrompt", route93);
  app.use("/api/production/workbench/getAudioBindAssetsList", route94);
  app.use("/api/production/workbench/getFileUrl", route95);
  app.use("/api/production/workbench/getGenerateData", route96);
  app.use("/api/production/workbench/getVideoList", route97);
  app.use("/api/production/workbench/selectVideo", route98);
  app.use("/api/production/workbench/updateVideoDuration", route99);
  app.use("/api/production/workbench/updateVideoPrompt", route100);
  app.use("/api/project/addDirectorManual", route101);
  app.use("/api/project/addProject", route102);
  app.use("/api/project/addVisualManual", route103);
  app.use("/api/project/deleteDirectorManual", route104);
  app.use("/api/project/deleteVisualManual", route105);
  app.use("/api/project/delProject", route106);
  app.use("/api/project/editDirectorlManual", route107);
  app.use("/api/project/editProject", route108);
  app.use("/api/project/editVisualManual", route109);
  app.use("/api/project/getModelDetails", route110);
  app.use("/api/project/getProject", route111);
  app.use("/api/project/getVisualManual", route112);
  app.use("/api/project/queryDirectorManual", route113);
  app.use("/api/project/visualManual", route114);
  app.use("/api/quickVideo/addShot", route115);
  app.use("/api/quickVideo/bindShotFirstFrame", route116);
  app.use("/api/quickVideo/confirmStage", route117);
  app.use("/api/quickVideo/createProject", route118);
  app.use("/api/quickVideo/createSession", route119);
  app.use("/api/quickVideo/getAssetBoard", route120);
  app.use("/api/quickVideo/getMediaUrls", route121);
  app.use("/api/quickVideo/getMetrics", route122);
  app.use("/api/quickVideo/getTimeline", route123);
  app.use("/api/quickVideo/getWorkbench", route124);
  app.use("/api/quickVideo/listSessions", route125);
  app.use("/api/quickVideo/removeShot", route126);
  app.use("/api/quickVideo/resolveAssets", route127);
  app.use("/api/quickVideo/retryShot", route128);
  app.use("/api/quickVideo/updateBrief", route129);
  app.use("/api/quickVideo/updateConfig", route130);
  app.use("/api/quickVideo/updateModels", route131);
  app.use("/api/quickVideo/updateSession", route132);
  app.use("/api/quickVideo/updateShot", route133);
  app.use("/api/register/register", route134);
  app.use("/api/script/addScript", route135);
  app.use("/api/script/batchAddScript", route136);
  app.use("/api/script/delScript", route137);
  app.use("/api/script/exportScript", route138);
  app.use("/api/script/extractAssets", route139);
  app.use("/api/script/getAiRegex", route140);
  app.use("/api/script/getScrptApi", route141);
  app.use("/api/script/pollScriptAssets", route142);
  app.use("/api/script/updateScript", route143);
  app.use("/api/scriptAgent/getPlanData", route144);
  app.use("/api/scriptAgent/setPlanData", route145);
  app.use("/api/scriptAgent/updateData", route146);
  app.use("/api/setting/about/checkUpdate", route147);
  app.use("/api/setting/about/downloadApp", route148);
  app.use("/api/setting/agentDeploy/agentSetKey", route149);
  app.use("/api/setting/agentDeploy/deployAgentModel", route150);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route151);
  app.use("/api/setting/agentDeploy/getAgentUseMode", route152);
  app.use("/api/setting/agentDeploy/updateAgentModel", route153);
  app.use("/api/setting/agentDeploy/updateUseMode", route154);
  app.use("/api/setting/dbConfig/clearData", route155);
  app.use("/api/setting/dbConfig/clearTable", route156);
  app.use("/api/setting/dbConfig/dbInfo", route157);
  app.use("/api/setting/dbConfig/exportData", route158);
  app.use("/api/setting/dbConfig/importData", route159);
  app.use("/api/setting/dev/getSwitchAiDevTool", route160);
  app.use("/api/setting/dev/updateSwitchAiDevTool", route161);
  app.use("/api/setting/fileManagement/openFolder", route162);
  app.use("/api/setting/getTextModel", route163);
  app.use("/api/setting/loginConfig/getUser", route164);
  app.use("/api/setting/loginConfig/updateUserPwd", route165);
  app.use("/api/setting/memoryConfig/delAllMemory", route166);
  app.use("/api/setting/memoryConfig/getMemory", route167);
  app.use("/api/setting/memoryConfig/sureMemory", route168);
  app.use("/api/setting/modelMap/bindingPrompt", route169);
  app.use("/api/setting/modelMap/deletePrompt", route170);
  app.use("/api/setting/modelMap/getImageAndVideoModel", route171);
  app.use("/api/setting/modelMap/getPromptList", route172);
  app.use("/api/setting/modelMap/savePrompt", route173);
  app.use("/api/setting/modelMap/updatePrompt", route174);
  app.use("/api/setting/promptManage/getPrompt", route175);
  app.use("/api/setting/promptManage/updatePrompt", route176);
  app.use("/api/setting/skillManagement/getSkillContent", route177);
  app.use("/api/setting/skillManagement/getSkillList", route178);
  app.use("/api/setting/skillManagement/saveSkillContent", route179);
  app.use("/api/setting/vendorConfig/addVendor", route180);
  app.use("/api/setting/vendorConfig/addVendorModel", route181);
  app.use("/api/setting/vendorConfig/addVendorModelSpec", route182);
  app.use("/api/setting/vendorConfig/deleteVendor", route183);
  app.use("/api/setting/vendorConfig/deleteVendorModelSpec", route184);
  app.use("/api/setting/vendorConfig/delVendorModel", route185);
  app.use("/api/setting/vendorConfig/enableVendor", route186);
  app.use("/api/setting/vendorConfig/getCodeByLink", route187);
  app.use("/api/setting/vendorConfig/getVendorList", route188);
  app.use("/api/setting/vendorConfig/modelTest", route189);
  app.use("/api/setting/vendorConfig/modelTest/imageTest", route190);
  app.use("/api/setting/vendorConfig/modelTest/textTest", route191);
  app.use("/api/setting/vendorConfig/modelTest/videoTest", route192);
  app.use("/api/setting/vendorConfig/updateCode", route193);
  app.use("/api/setting/vendorConfig/updateVendorInputs", route194);
  app.use("/api/setting/vendorConfig/updateVendorModelSpec", route195);
  app.use("/api/setting/vendorConfig/upVendorModel", route196);
  app.use("/api/task/getProject", route197);
  app.use("/api/task/getTaskApi", route198);
  app.use("/api/task/getTaskCategories", route199);
  app.use("/api/task/taskDetails", route200);
  app.use("/api/test/test", route201);
  app.use("/api/quickVideo/generateConfirm", route202);
}
